"""empty message

Revision ID: 3aa480951340
Revises: 
Create Date: 2020-05-19 15:40:25.788992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa480951340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('href_df',
    sa.Column('id_href', sa.Integer(), nullable=False),
    sa.Column('href', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_href')
    )
    op.create_table('images',
    sa.Column('id_images', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_images')
    )
    op.create_table('ingredient',
    sa.Column('id_ingrediente', sa.Integer(), nullable=False),
    sa.Column('ingrediente', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_ingrediente')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id_recipe_ingredient', sa.Integer(), nullable=False),
    sa.Column('id_recipe', sa.Integer(), nullable=True),
    sa.Column('id_ingredient', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_recipe_ingredient')
    )
    op.create_table('recipes_df',
    sa.Column('id_recipes_df', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('tempo_preparo', sa.Text(), nullable=True),
    sa.Column('rendimento', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('modo_preparo', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('ingredientes', sa.Text(), nullable=True),
    sa.Column('qtd_ingrediente', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_recipes_df')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_df')
    op.drop_table('recipe_ingredient')
    op.drop_table('ingredient')
    op.drop_table('images')
    op.drop_table('href_df')
    # ### end Alembic commands ###
